services:
  server:
    build:
      context: ../server
      dockerfile: Dockerfile
    container_name: ws_server
    env_file:
      - ../server/.env
    environment:
      - NODE_ENV=dev
      - SSL_KEY=/etc/ssl/server.key
      - SSL_CERT=/etc/ssl/server.crt
      - HOST=mysql
      - USER=user
      - PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ${SSL_KEY_PATH}:/etc/ssl/server.key:ro
      - ${SSL_CRT_PATH}:/etc/ssl/server.crt:ro
    networks:
      - my_network

  mysql:
    image: mysql:8
    container_name: ws_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network
    
  nginx:
    build:
      context: ../web
      dockerfile: Dockerfile
    container_name: ws_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SSL_KEY_PATH}:/etc/ssl/server.key:ro
      - ${SSL_CRT_PATH}:/etc/ssl/server.crt:ro
    depends_on:
      - server
    networks:
      - my_network
volumes:
  mysql_data:

networks:
  my_network:
    driver: bridge
